config/routes.rb
Startupality::Application.routes.draw do
  root :to => 'angular#angular'
  match 'angular/angular' => 'angular#angular'

  devise_for :users, :controllers => { :sessions => "sessions", :registrations => "registrations" }
  devise_scope :user do get "/registrations/notification" => "registrations#notification" end

  resources :users

  namespace :api do
    resources :instructional_videos
    resources :section_types
    resources :checklist_steps
    resources :projects do
      collection do
        get 'getActivated'
      end
      resources :sections do
        resources :section_types
      end
      resources :risks
      resources :revenueOrExpenses
      resources :expenses
      resources :cards
      resources :hypotheses
      resources :project_checklist_steps
      resources :register_risks
    end

    resources :userutil do
      post :fetch_current_user, :on => :collection
      get :get_users_select2, :on => :collection
    end

  end

end

app/models/project_checklist_step.rb
class ProjectChecklistStep < ActiveRecord::Base
  attr_accessible :done, :project_id, :stepNumber, :value, :checklist_step_id
  belongs_to :project
  belongs_to :checklist_step

  def as_json(options={})
    {
        :id => self.id,
        :done => self.done,
        :stepNumber => self.stepNumber,
        :value => self.value,
        :project_id => self.project_id,
        :project => self.project,
        :checklist_step => self.checklist_step
    }
  end
end

app/controllers/api/project_checklist_steps_controller.rb
class Api::ProjectChecklistStepsController < ApplicationController
  before_filter :load_parent

  def load_parent
    @project = Project.find(params[:project_id])
  end

  # GET /project_checklist_steps
  # GET /project_checklist_steps.json
  def index
    @project_checklist_steps = @project.project_checklist_steps.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @project_checklist_steps }
    end
  end

  # GET /project_checklist_steps/1
  # GET /project_checklist_steps/1.json
  def show
    @project_checklist_step = @project.project_checklist_steps.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @project_checklist_step }
    end
  end

  # GET /project_checklist_steps/new
  # GET /project_checklist_steps/new.json
  def new
    @project_checklist_step = @project.project_checklist_steps.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @project_checklist_step }
    end
  end

  # GET /project_checklist_steps/1/edit
  def edit
    @project_checklist_step = @project.project_checklist_steps.find(params[:id])
  end

  # POST /project_checklist_steps
  # POST /project_checklist_steps.json
  def create
    @project_checklist_step = @project.project_checklist_steps.new(params[:project_checklist_step])

    respond_to do |format|
      if @project_checklist_step.save
        format.html { redirect_to @project_checklist_step, notice: 'Project checklist step was successfully created.' }
        format.json { render json: @project_checklist_step, status: :created}
      else
        format.html { render action: "new" }
        format.json { render json: @project_checklist_step.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /project_checklist_steps/1
  # PUT /project_checklist_steps/1.json
  def update
    @project_checklist_step = @project.project_checklist_steps.find(params[:id])

    respond_to do |format|
      if @project_checklist_step.update_attributes(params[:project_checklist_step])
        format.html { redirect_to @project_checklist_step, notice: 'Project checklist step was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @project_checklist_step.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /project_checklist_steps/1
  # DELETE /project_checklist_steps/1.json
  def destroy
    @project_checklist_step = @project.project_checklist_steps.find(params[:id])
    @project_checklist_step.destroy

    respond_to do |format|
      format.html { redirect_to project_checklist_steps_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/project_checklist_steps_controller.rb
class ProjectChecklistStepsController < ApplicationController
  before_filter :load_parent

  def load_parent
    @project = Project.find(params[:project_id])
  end

  # GET /project_checklist_steps
  # GET /project_checklist_steps.json
  def index
    @project_checklist_steps = @project.project_checklist_steps.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @project_checklist_steps }
    end
  end

  # GET /project_checklist_steps/1
  # GET /project_checklist_steps/1.json
  def show
    @project_checklist_step = @project.project_checklist_steps.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @project_checklist_step }
    end
  end

  # GET /project_checklist_steps/new
  # GET /project_checklist_steps/new.json
  def new
    @project_checklist_step = @project.project_checklist_steps.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @project_checklist_step }
    end
  end

  # GET /project_checklist_steps/1/edit
  def edit
    @project_checklist_step = @project.project_checklist_steps.find(params[:id])
  end

  # POST /project_checklist_steps
  # POST /project_checklist_steps.json
  def create
    @project_checklist_step = @project.project_checklist_steps.new(params[:project_checklist_step])

    respond_to do |format|
      if @project_checklist_step.save
        format.html { redirect_to @project_checklist_step, notice: 'Project checklist step was successfully created.' }
        format.json { render json: @project_checklist_step, status: :created}
      else
        format.html { render action: "new" }
        format.json { render json: @project_checklist_step.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /project_checklist_steps/1
  # PUT /project_checklist_steps/1.json
  def update
    @project_checklist_step = @project.project_checklist_steps.find(params[:id])

    respond_to do |format|
      if @project_checklist_step.update_attributes(params[:project_checklist_step])
        format.html { redirect_to @project_checklist_step, notice: 'Project checklist step was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @project_checklist_step.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /project_checklist_steps/1
  # DELETE /project_checklist_steps/1.json
  def destroy
    @project_checklist_step = @project.project_checklist_steps.find(params[:id])
    @project_checklist_step.destroy

    respond_to do |format|
      format.html { redirect_to project_checklist_steps_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/project_checklist_steps_helper.rb
module ProjectChecklistStepsHelper
end

app/views/project_checklist_steps/_form.html.erb
<%= form_for(@project_checklist_step) do |f| %>
  <% if @project_checklist_step.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project_checklist_step.errors.count, "error") %> prohibited this project_checklist_step from being saved:</h2>

      <ul>
      <% @project_checklist_step.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :value %><br />
    <%= f.text_field :value %>
  </div>
  <div class="field">
    <%= f.label :done %><br />
    <%= f.check_box :done %>
  </div>
  <div class="field">
    <%= f.label :sectionTypeIdentifier %><br />
    <%= f.text_field :sectionTypeIdentifier %>
  </div>
  <div class="field">
    <%= f.label :project_id %><br />
    <%= f.number_field :project_id %>
  </div>
  <div class="field">
    <%= f.label :stepNumber %><br />
    <%= f.number_field :stepNumber %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/project_checklist_steps/edit.html.erb
<h1>Editing project_checklist_step</h1>

<%= render 'form' %>

<%= link_to 'Show', @project_checklist_step %> |
<%= link_to 'Back', project_checklist_steps_path %>

app/views/project_checklist_steps/index.html.erb
<h1>Listing project_checklist_steps</h1>

<table>
  <tr>
    <th>Value</th>
    <th>Done</th>
    <th>Sectiontypeidentifier</th>
    <th>Project</th>
    <th>Stepnumber</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @project_checklist_steps.each do |project_checklist_step| %>
  <tr>
    <td><%= project_checklist_step.value %></td>
    <td><%= project_checklist_step.done %></td>
    <td><%= project_checklist_step.sectionTypeIdentifier %></td>
    <td><%= project_checklist_step.project_id %></td>
    <td><%= project_checklist_step.stepNumber %></td>
    <td><%= link_to 'Show', project_checklist_step %></td>
    <td><%= link_to 'Edit', edit_project_checklist_step_path(project_checklist_step) %></td>
    <td><%= link_to 'Destroy', project_checklist_step, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Project checklist step', new_project_checklist_step_path %>

app/views/project_checklist_steps/new.html.erb
<h1>New project_checklist_step</h1>

<%= render 'form' %>

<%= link_to 'Back', project_checklist_steps_path %>

app/views/project_checklist_steps/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Value:</b>
  <%= @project_checklist_step.value %>
</p>

<p>
  <b>Done:</b>
  <%= @project_checklist_step.done %>
</p>

<p>
  <b>Sectiontypeidentifier:</b>
  <%= @project_checklist_step.sectionTypeIdentifier %>
</p>

<p>
  <b>Project:</b>
  <%= @project_checklist_step.project_id %>
</p>

<p>
  <b>Stepnumber:</b>
  <%= @project_checklist_step.stepNumber %>
</p>


<%= link_to 'Edit', edit_project_checklist_step_path(@project_checklist_step) %> |
<%= link_to 'Back', project_checklist_steps_path %>