config/routes.rb
Startupality::Application.routes.draw do
  root :to => 'angular#angular'
  match 'angular/angular' => 'angular#angular'

  devise_for :users, :controllers => { :sessions => "sessions", :registrations => "registrations" }
  devise_scope :user do get "/registrations/notification" => "registrations#notification" end

  resources :users

  namespace :api do
    resources :instructional_videos
    resources :section_types
    resources :checklist_steps
    resources :projects do
      collection do
        get 'getActivated'
      end
      resources :sections do
        resources :section_types
      end
      resources :risks
      resources :revenueOrExpenses
      resources :expenses
      resources :cards
      resources :hypotheses
      resources :project_checklist_steps
      resources :register_risks
    end

    resources :userutil do
      post :fetch_current_user, :on => :collection
      get :get_users_select2, :on => :collection
    end

  end

end

app/models/section.rb
class Section < ActiveRecord::Base
  attr_accessible :data, :project_id, :tags, :section_type_id
  belongs_to :project
  belongs_to :section_type

  def as_json(options={})
    {
        :id => self.id,
        :data => self.data,
        :tags => self.tags,
        :project_id => self.project_id,
        :project => self.project,
        :section_type => self.section_type
    }
  end
end

app/models/section_type.rb
class SectionType < ActiveRecord::Base
  attr_accessible :description, :questions, :title, :stringIdentifier, :order, :examples
  has_many :sections, :dependent => :destroy
  has_many :checklist_steps, :dependent => :destroy
  has_many :instructional_videos, :dependent => :destroy
end

app/controllers/api/sections_controller.rb
class Api::SectionsController < ApplicationController
  before_filter :load_parent

  def load_parent
    @project = Project.find(params[:project_id])
  end

  # GET /sections
  # GET /sections.json
  def index
    @sections = @project.sections.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @sections }
    end
  end

  # GET /sections/1
  # GET /sections/1.json
  def show
    @section = @project.sections.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @section }
    end
  end

  # GET /sections/new
  # GET /sections/new.json
  def new
    @section = @project.sections.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @section }
    end
  end

  # GET /sections/1/edit
  def edit
    @section = @project.sections.find(params[:id])
  end

  # POST /sections
  # POST /sections.json
  def create
    @section = @project.sections.new(params[:section])

    respond_to do |format|
      if @section.save
        format.html { redirect_to @section, notice: 'Section was successfully created.' }
        format.json { render json: @section, status: :created}
      else
        format.html { render action: "new" }
        format.json { render json: @section.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /sections/1
  # PUT /sections/1.json
  def update
    @section = @project.sections.find(params[:id])

    respond_to do |format|
      # Because nested attributes were received, except them from the update to not have different model type when updating
      if @section.update_attributes(params[:section])
        format.html { redirect_to @section, notice: 'Section was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @section.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sections/1
  # DELETE /sections/1.json
  def destroy
    @section = @project.sections.find(params[:id])
    @section.destroy

    respond_to do |format|
      format.html { redirect_to sections_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/sections_controller.rb
class SectionsController < ApplicationController
  before_filter :load_parent

  def load_parent
    @project = Project.find(params[:project_id])
  end

  # GET /sections
  # GET /sections.json
  def index
    @sections = @project.sections.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @sections }
    end
  end

  # GET /sections/1
  # GET /sections/1.json
  def show
    @section = @project.sections.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @section }
    end
  end

  # GET /sections/new
  # GET /sections/new.json
  def new
    @section = @project.sections.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @section }
    end
  end

  # GET /sections/1/edit
  def edit
    @section = @project.sections.find(params[:id])
  end

  # POST /sections
  # POST /sections.json
  def create
    @section = @project.sections.new(params[:section])

    respond_to do |format|
      if @section.save
        format.html { redirect_to @section, notice: 'Section was successfully created.' }
        format.json { render json: @section, status: :created}
      else
        format.html { render action: "new" }
        format.json { render json: @section.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /sections/1
  # PUT /sections/1.json
  def update
    @section = @project.sections.find(params[:id])

    respond_to do |format|
      # Because nested attributes were received, except them from the update to not have different model type when updating
      if @section.update_attributes(params[:section])
        format.html { redirect_to @section, notice: 'Section was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @section.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sections/1
  # DELETE /sections/1.json
  def destroy
    @section = @project.sections.find(params[:id])
    @section.destroy

    respond_to do |format|
      format.html { redirect_to sections_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/sections_helper.rb
module SectionsHelper
end

app/views/sections/_form.html.erb
<%= form_for(@section) do |f| %>
  <% if @section.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@section.errors.count, "error") %> prohibited this section from being saved:</h2>

      <ul>
      <% @section.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :data %><br />
    <%= f.text_area :data %>
  </div>
  <div class="field">
    <%= f.label :project_id %><br />
    <%= f.number_field :project_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sections/edit.html.erb
<h1>Editing section</h1>

<%= render 'form' %>

<%= link_to 'Show', @section %> |
<%= link_to 'Back', sections_path %>

app/views/sections/index.html.erb
<h1>Listing sections</h1>

<table>
  <tr>
    <th>Data</th>
    <th>Project</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @sections.each do |section| %>
  <tr>
    <td><%= section.data %></td>
    <td><%= section.project_id %></td>
    <td><%= link_to 'Show', section %></td>
    <td><%= link_to 'Edit', edit_section_path(section) %></td>
    <td><%= link_to 'Destroy', section, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Section', new_section_path %>

app/views/sections/new.html.erb
<h1>New section</h1>

<%= render 'form' %>

<%= link_to 'Back', sections_path %>

app/views/sections/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Data:</b>
  <%= @section.data %>
</p>

<p>
  <b>Project:</b>
  <%= @section.project_id %>
</p>


<%= link_to 'Edit', edit_section_path(@section) %> |
<%= link_to 'Back', sections_path %>