config/routes.rb
Startupality::Application.routes.draw do
  root :to => 'angular#angular'
  match 'angular/angular' => 'angular#angular'

  devise_for :users, :controllers => { :sessions => "sessions", :registrations => "registrations" }
  devise_scope :user do get "/registrations/notification" => "registrations#notification" end

  resources :users

  namespace :api do
    resources :instructional_videos
    resources :section_types
    resources :checklist_steps
    resources :projects do
      collection do
        get 'getActivated'
      end
      resources :sections do
        resources :section_types
      end
      resources :risks
      resources :revenueOrExpenses
      resources :expenses
      resources :cards
      resources :hypotheses
      resources :project_checklist_steps
      resources :register_risks
    end

    resources :userutil do
      post :fetch_current_user, :on => :collection
      get :get_users_select2, :on => :collection
    end

  end

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
        if user.role == "partner" or user.role == "admin" or user.role == "normal-user"
             can :manage, :all
        else
            can :edit, Script do |script|
                script.user_id==user.id
            end
            can :delete, Script do |script|
                script.user_id==user.id
            end
            can :view,:all
            can :review,:all 
        end
    end
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  
end

app/models/card.rb
class Card < ActiveRecord::Base
  attr_accessible :board, :project_id, :title, :order
  belongs_to :project
end

app/models/checklist_step.rb
class ChecklistStep < ActiveRecord::Base
  attr_accessible :title, :stepNumber, :project_checklist_step, :section_type
  has_many :project_checklist_step
  belongs_to :section_type

  def as_json(options={})
    {
        :id => self.id,
        :title => self.title,
        :stepNumber => self.stepNumber,
        :section_type => self.section_type,
    }
  end
end

app/models/hypothesis.rb
class Hypothesis < ActiveRecord::Base
  attr_accessible :board, :project_id, :title, :order
  belongs_to :project
end

app/models/instructional_video.rb
class InstructionalVideo < ActiveRecord::Base
  attr_accessible :url
  belongs_to :section_type
end

app/models/model.rb
class Model < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/project.rb
class Project < ActiveRecord::Base
  attr_accessible :activated, :title
  belongs_to :user
  has_many :sections, :dependent => :destroy
  has_many :risks, :dependent => :destroy
  has_many :revenue_or_expenses, :dependent => :destroy
  has_many :cards, :dependent => :destroy
  has_many :hypotheses, :dependent => :destroy
  has_many :project_checklist_steps, :dependent => :destroy
  has_many :register_risks, :dependent => :destroy
end

app/models/register_risk.rb
class RegisterRisk < ActiveRecord::Base
  attr_accessible :name, :probability, :impact, :responseAction, :project_id
  belongs_to :project
end

app/models/revenue_or_expense.rb
class RevenueOrExpense < ActiveRecord::Base
  attr_accessible :april, :august, :december, :january, :february, :july, :june, :march, :may, :november, :october, :project_id, :rowName, :rowNumber, :september, :year, :isExpense
  belongs_to :project
end

app/models/risk.rb
class Risk < ActiveRecord::Base
  attr_accessible :opportunitiesEconomical, :opportunitiesPolitical, :opportunitiesSociological, :opportunitiesTechnical, :project_id, :strengths, :threatsEconomical, :threatsPolitical, :threatsSociological, :threatsTechnical, :weaknesses
  belongs_to :project
end

app/models/section.rb
class Section < ActiveRecord::Base
  attr_accessible :data, :project_id, :tags, :section_type_id
  belongs_to :project
  belongs_to :section_type

  def as_json(options={})
    {
        :id => self.id,
        :data => self.data,
        :tags => self.tags,
        :project_id => self.project_id,
        :project => self.project,
        :section_type => self.section_type
    }
  end
end

app/models/section_type.rb
class SectionType < ActiveRecord::Base
  attr_accessible :description, :questions, :title, :stringIdentifier, :order, :examples
  has_many :sections, :dependent => :destroy
  has_many :checklist_steps, :dependent => :destroy
  has_many :instructional_videos, :dependent => :destroy
end

app/models/user.rb
class User < ActiveRecord::Base
	ROLES = %w[partner admin normal-user premium-user]
	# Include default devise modules. Others available are:
	# :token_authenticatable, :confirmable,
	# :lockable, :timeoutable and :omniauthable
  has_many :projects, :dependent => :destroy
	devise :database_authenticatable, :registerable, :confirmable,
				 :recoverable, :rememberable, :trackable, :validatable

	# Setup accessible (or protected) attributes for your model
	attr_accessible :email, :password, :password_confirmation, :role,:remember_me
	validates :email, :presence => true, :uniqueness => true,
                      :format => {:with => /^([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})$/i}
	before_validation :downcase_email
		def downcase_email
			self.email = self.email.downcase if self.email.present?
    end

  after_create :register_hook

  def confirm!
    super
    default_role
  end

  def default_role
    self.role = "normal-user"
    self.save
  end

  def register_hook
    @just_signed_up = true

    Analytics.identify(
        user_id: self.id,
        traits: { email: self.email, name: self.full_name}
    )
    Analytics.track(
        user_id: self.id,
        event: 'Registered'
    )
  end

  def login_hook
    if (Time.new - self.last_sign_in_at) < 600 # seconds, so 10 minutes
    else
      # do other stuff, probably a redirect
      # possibly  sign_out_and_redirect(resource_name)
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
	def flash_div(kind)
		unless flash[kind].blank?
			text = "<p>#{flash[kind]}</p>"
			content_tag :div, text.html_safe, :id => "flash", :class => kind
		end
	end
	def current_navigation expected_path
		if params[:controller] ==expected_path
			return "active"
		else
			return ""
		end
	end
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/hypotheses_helper.rb
module HypothesesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/revenues_helper.rb
module RevenuesHelper
end

app/helpers/risks_helper.rb
module RisksHelper
end

app/helpers/script_files_helper.rb
module ScriptFilesHelper
end

app/helpers/sections_helper.rb
module SectionsHelper
end

app/views/revenues/_form.html.erb
<%= form_for(@revenue) do |f| %>
  <% if @revenue.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@revenue.errors.count, "error") %> prohibited this revenue from being saved:</h2>

      <ul>
      <% @revenue.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :rowNumber %><br />
    <%= f.number_field :rowNumber %>
  </div>
  <div class="field">
    <%= f.label :rowName %><br />
    <%= f.text_field :rowName %>
  </div>
  <div class="field">
    <%= f.label :project_id %><br />
    <%= f.text_field :project_id %>
  </div>
  <div class="field">
    <%= f.label :february %><br />
    <%= f.number_field :february %>
  </div>
  <div class="field">
    <%= f.label :march %><br />
    <%= f.number_field :march %>
  </div>
  <div class="field">
    <%= f.label :april %><br />
    <%= f.number_field :april %>
  </div>
  <div class="field">
    <%= f.label :may %><br />
    <%= f.number_field :may %>
  </div>
  <div class="field">
    <%= f.label :june %><br />
    <%= f.number_field :june %>
  </div>
  <div class="field">
    <%= f.label :july %><br />
    <%= f.number_field :july %>
  </div>
  <div class="field">
    <%= f.label :august %><br />
    <%= f.number_field :august %>
  </div>
  <div class="field">
    <%= f.label :september %><br />
    <%= f.number_field :september %>
  </div>
  <div class="field">
    <%= f.label :october %><br />
    <%= f.number_field :october %>
  </div>
  <div class="field">
    <%= f.label :november %><br />
    <%= f.number_field :november %>
  </div>
  <div class="field">
    <%= f.label :december %><br />
    <%= f.number_field :december %>
  </div>
  <div class="field">
    <%= f.label :year %><br />
    <%= f.number_field :year %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/revenues/edit.html.erb
<h1>Editing revenue</h1>

<%= render 'form' %>

<%= link_to 'Show', @revenue %> |
<%= link_to 'Back', revenues_path %>

app/views/revenues/index.html.erb
<h1>Listing revenues</h1>

<table>
  <tr>
    <th>Rownumber</th>
    <th>Rowname</th>
    <th>Project</th>
    <th>February</th>
    <th>March</th>
    <th>April</th>
    <th>May</th>
    <th>June</th>
    <th>July</th>
    <th>August</th>
    <th>September</th>
    <th>October</th>
    <th>November</th>
    <th>December</th>
    <th>Year</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @revenues.each do |revenue| %>
  <tr>
    <td><%= revenue.rowNumber %></td>
    <td><%= revenue.rowName %></td>
    <td><%= revenue.project_id %></td>
    <td><%= revenue.february %></td>
    <td><%= revenue.march %></td>
    <td><%= revenue.april %></td>
    <td><%= revenue.may %></td>
    <td><%= revenue.june %></td>
    <td><%= revenue.july %></td>
    <td><%= revenue.august %></td>
    <td><%= revenue.september %></td>
    <td><%= revenue.october %></td>
    <td><%= revenue.november %></td>
    <td><%= revenue.december %></td>
    <td><%= revenue.year %></td>
    <td><%= link_to 'Show', revenue %></td>
    <td><%= link_to 'Edit', edit_revenue_path(revenue) %></td>
    <td><%= link_to 'Destroy', revenue, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Revenue', new_revenue_path %>

app/views/revenues/new.html.erb
<h1>New revenue</h1>

<%= render 'form' %>

<%= link_to 'Back', revenues_path %>

app/views/revenues/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Rownumber:</b>
  <%= @revenue.rowNumber %>
</p>

<p>
  <b>Rowname:</b>
  <%= @revenue.rowName %>
</p>

<p>
  <b>Project:</b>
  <%= @revenue.project_id %>
</p>

<p>
  <b>February:</b>
  <%= @revenue.february %>
</p>

<p>
  <b>March:</b>
  <%= @revenue.march %>
</p>

<p>
  <b>April:</b>
  <%= @revenue.april %>
</p>

<p>
  <b>May:</b>
  <%= @revenue.may %>
</p>

<p>
  <b>June:</b>
  <%= @revenue.june %>
</p>

<p>
  <b>July:</b>
  <%= @revenue.july %>
</p>

<p>
  <b>August:</b>
  <%= @revenue.august %>
</p>

<p>
  <b>September:</b>
  <%= @revenue.september %>
</p>

<p>
  <b>October:</b>
  <%= @revenue.october %>
</p>

<p>
  <b>November:</b>
  <%= @revenue.november %>
</p>

<p>
  <b>December:</b>
  <%= @revenue.december %>
</p>

<p>
  <b>Year:</b>
  <%= @revenue.year %>
</p>


<%= link_to 'Edit', edit_revenue_path(@revenue) %> |
<%= link_to 'Back', revenues_path %>

app/views/users/shared/_links.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Sign in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>